package top.maybe123.pojo;

public class Articles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_author
     *
     * @mbg.generated
     */
    private String articleAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_classify
     *
     * @mbg.generated
     */
    private String articleClassify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article
     *
     * @mbg.generated
     */
    private String article;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.Id
     *
     * @return the value of articles.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.Id
     *
     * @param id the value for articles.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_title
     *
     * @return the value of articles.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_title
     *
     * @param articleTitle the value for articles.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_author
     *
     * @return the value of articles.article_author
     *
     * @mbg.generated
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_author
     *
     * @param articleAuthor the value for articles.article_author
     *
     * @mbg.generated
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor == null ? null : articleAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_classify
     *
     * @return the value of articles.article_classify
     *
     * @mbg.generated
     */
    public String getArticleClassify() {
        return articleClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_classify
     *
     * @param articleClassify the value for articles.article_classify
     *
     * @mbg.generated
     */
    public void setArticleClassify(String articleClassify) {
        this.articleClassify = articleClassify == null ? null : articleClassify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article
     *
     * @return the value of articles.article
     *
     * @mbg.generated
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article
     *
     * @param article the value for articles.article
     *
     * @mbg.generated
     */
    public void setArticle(String article) {
        this.article = article == null ? null : article.trim();
    }
}