package top.maybe123.pojo;

public class MyCg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_id
     *
     * @mbg.generated
     */
    private Integer cgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_name
     *
     * @mbg.generated
     */
    private String cgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_addr
     *
     * @mbg.generated
     */
    private String cgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_time
     *
     * @mbg.generated
     */
    private String cgTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_phone
     *
     * @mbg.generated
     */
    private String cgPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_cg.cg_lxr
     *
     * @mbg.generated
     */
    private String cgLxr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_id
     *
     * @return the value of my_cg.cg_id
     *
     * @mbg.generated
     */
    public Integer getCgId() {
        return cgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_id
     *
     * @param cgId the value for my_cg.cg_id
     *
     * @mbg.generated
     */
    public void setCgId(Integer cgId) {
        this.cgId = cgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_name
     *
     * @return the value of my_cg.cg_name
     *
     * @mbg.generated
     */
    public String getCgName() {
        return cgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_name
     *
     * @param cgName the value for my_cg.cg_name
     *
     * @mbg.generated
     */
    public void setCgName(String cgName) {
        this.cgName = cgName == null ? null : cgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_addr
     *
     * @return the value of my_cg.cg_addr
     *
     * @mbg.generated
     */
    public String getCgAddr() {
        return cgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_addr
     *
     * @param cgAddr the value for my_cg.cg_addr
     *
     * @mbg.generated
     */
    public void setCgAddr(String cgAddr) {
        this.cgAddr = cgAddr == null ? null : cgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_time
     *
     * @return the value of my_cg.cg_time
     *
     * @mbg.generated
     */
    public String getCgTime() {
        return cgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_time
     *
     * @param cgTime the value for my_cg.cg_time
     *
     * @mbg.generated
     */
    public void setCgTime(String cgTime) {
        this.cgTime = cgTime == null ? null : cgTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_phone
     *
     * @return the value of my_cg.cg_phone
     *
     * @mbg.generated
     */
    public String getCgPhone() {
        return cgPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_phone
     *
     * @param cgPhone the value for my_cg.cg_phone
     *
     * @mbg.generated
     */
    public void setCgPhone(String cgPhone) {
        this.cgPhone = cgPhone == null ? null : cgPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_cg.cg_lxr
     *
     * @return the value of my_cg.cg_lxr
     *
     * @mbg.generated
     */
    public String getCgLxr() {
        return cgLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_cg.cg_lxr
     *
     * @param cgLxr the value for my_cg.cg_lxr
     *
     * @mbg.generated
     */
    public void setCgLxr(String cgLxr) {
        this.cgLxr = cgLxr == null ? null : cgLxr.trim();
    }
}