package top.maybe123.pojo;

public class MySp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_id
     *
     * @mbg.generated
     */
    private Integer spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_name
     *
     * @mbg.generated
     */
    private String spName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_xx
     *
     * @mbg.generated
     */
    private String spXx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_fhdz
     *
     * @mbg.generated
     */
    private String spFhdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_price
     *
     * @mbg.generated
     */
    private String spPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_time
     *
     * @mbg.generated
     */
    private String spTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_sp.sp_mf
     *
     * @mbg.generated
     */
    private String spMf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_id
     *
     * @return the value of my_sp.sp_id
     *
     * @mbg.generated
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_id
     *
     * @param spId the value for my_sp.sp_id
     *
     * @mbg.generated
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_name
     *
     * @return the value of my_sp.sp_name
     *
     * @mbg.generated
     */
    public String getSpName() {
        return spName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_name
     *
     * @param spName the value for my_sp.sp_name
     *
     * @mbg.generated
     */
    public void setSpName(String spName) {
        this.spName = spName == null ? null : spName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_xx
     *
     * @return the value of my_sp.sp_xx
     *
     * @mbg.generated
     */
    public String getSpXx() {
        return spXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_xx
     *
     * @param spXx the value for my_sp.sp_xx
     *
     * @mbg.generated
     */
    public void setSpXx(String spXx) {
        this.spXx = spXx == null ? null : spXx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_fhdz
     *
     * @return the value of my_sp.sp_fhdz
     *
     * @mbg.generated
     */
    public String getSpFhdz() {
        return spFhdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_fhdz
     *
     * @param spFhdz the value for my_sp.sp_fhdz
     *
     * @mbg.generated
     */
    public void setSpFhdz(String spFhdz) {
        this.spFhdz = spFhdz == null ? null : spFhdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_price
     *
     * @return the value of my_sp.sp_price
     *
     * @mbg.generated
     */
    public String getSpPrice() {
        return spPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_price
     *
     * @param spPrice the value for my_sp.sp_price
     *
     * @mbg.generated
     */
    public void setSpPrice(String spPrice) {
        this.spPrice = spPrice == null ? null : spPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_time
     *
     * @return the value of my_sp.sp_time
     *
     * @mbg.generated
     */
    public String getSpTime() {
        return spTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_time
     *
     * @param spTime the value for my_sp.sp_time
     *
     * @mbg.generated
     */
    public void setSpTime(String spTime) {
        this.spTime = spTime == null ? null : spTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sp.sp_mf
     *
     * @return the value of my_sp.sp_mf
     *
     * @mbg.generated
     */
    public String getSpMf() {
        return spMf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sp.sp_mf
     *
     * @param spMf the value for my_sp.sp_mf
     *
     * @mbg.generated
     */
    public void setSpMf(String spMf) {
        this.spMf = spMf == null ? null : spMf.trim();
    }
}