package top.maybe123.pojo;

public class MyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_zh
     *
     * @mbg.generated
     */
    private String userZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_pass
     *
     * @mbg.generated
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_xm
     *
     * @mbg.generated
     */
    private String userXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_addr
     *
     * @mbg.generated
     */
    private String userAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_choose
     *
     * @mbg.generated
     */
    private Integer userChoose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_id
     *
     * @return the value of my_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_id
     *
     * @param userId the value for my_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_zh
     *
     * @return the value of my_user.user_zh
     *
     * @mbg.generated
     */
    public String getUserZh() {
        return userZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_zh
     *
     * @param userZh the value for my_user.user_zh
     *
     * @mbg.generated
     */
    public void setUserZh(String userZh) {
        this.userZh = userZh == null ? null : userZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_pass
     *
     * @return the value of my_user.user_pass
     *
     * @mbg.generated
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_pass
     *
     * @param userPass the value for my_user.user_pass
     *
     * @mbg.generated
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_xm
     *
     * @return the value of my_user.user_xm
     *
     * @mbg.generated
     */
    public String getUserXm() {
        return userXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_xm
     *
     * @param userXm the value for my_user.user_xm
     *
     * @mbg.generated
     */
    public void setUserXm(String userXm) {
        this.userXm = userXm == null ? null : userXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_phone
     *
     * @return the value of my_user.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_phone
     *
     * @param userPhone the value for my_user.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_addr
     *
     * @return the value of my_user.user_addr
     *
     * @mbg.generated
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_addr
     *
     * @param userAddr the value for my_user.user_addr
     *
     * @mbg.generated
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr == null ? null : userAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_choose
     *
     * @return the value of my_user.user_choose
     *
     * @mbg.generated
     */
    public Integer getUserChoose() {
        return userChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_choose
     *
     * @param userChoose the value for my_user.user_choose
     *
     * @mbg.generated
     */
    public void setUserChoose(Integer userChoose) {
        this.userChoose = userChoose;
    }
}