package top.maybe123.dao;

import java.util.List;
import top.maybe123.pojo.MyCg;

public interface MyCgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_cg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_cg
     *
     * @mbg.generated
     */
    int insert(MyCg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_cg
     *
     * @mbg.generated
     */
    MyCg selectByPrimaryKey(Integer cgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_cg
     *
     * @mbg.generated
     */
    List<MyCg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_cg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyCg record);
}