package top.maybe123.dao;

import java.util.List;
import top.maybe123.pojo.MyImage;

public interface MyImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_image
     *
     * @mbg.generated
     */
    int insert(MyImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_image
     *
     * @mbg.generated
     */
    MyImage selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_image
     *
     * @mbg.generated
     */
    List<MyImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyImage record);
}