package top.maybe123.dao;

import java.util.List;
import top.maybe123.pojo.MySp;

public interface MySpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_sp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_sp
     *
     * @mbg.generated
     */
    int insert(MySp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_sp
     *
     * @mbg.generated
     */
    MySp selectByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_sp
     *
     * @mbg.generated
     */
    List<MySp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_sp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MySp record);
}