package top.maybe123.dao;

import java.util.List;
import top.maybe123.pojo.MyUser;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    MyUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    List<MyUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyUser record);
}